require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'adsync.gemspec'
    - 'bin/adsync'
